Fix unit tests and re-enable tests in CI
18F/analytics-reporter pull request #767
Opened 2024-01-29 18:59 UTC by levinmr

2024-01-29 19:00 UTC, levinmr commented
There are still a few unit tests to fix here.  Not ready for merge yet.

2024-01-30 16:38 UTC, scottqueen-bixal requested changes

2024-01-30 16:38 UTC, scottqueen-bixal commented on test/process-results/ga-data-processor.test.js
> +      debugger;
do we want these debuggers?

2024-01-30 16:38 UTC, scottqueen-bixal commented on test/process-results/result-formatter.test.js
> +        debugger;
do we want these debuggers?

2024-01-30 16:38 UTC, scottqueen-bixal commented on .mocharc.yml
> +  - 'test/**/*.js'
Can we configure to include the test for the ua app?

```suggestion
  - 'test/**/*.js'
  - 'ua/src/**/*.js'
  - 'ua/test/**/*.js'
```

2024-01-30 16:38 UTC, scottqueen-bixal commented on README.md
> +#### Running unit tests locally
nice, worked perfectly

2024-01-30 19:06 UTC, scottqueen-bixal approved these changes

2024-01-30 19:08 UTC, merged